In [ ]:
%%bash

MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh
MINICONDA_PREFIX=/usr/local
wget https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT
chmod +x $MINICONDA_INSTALLER_SCRIPT
./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX

PREFIX=/usr/local
installing: python-3.6.5-hc3d631a_2 ...
installing: ca-certificates-2018.03.07-0 ...
installing: conda-env-2.6.0-h36134e3_1 ...
installing: libgcc-ng-7.2.0-hdf63c60_3 ...
installing: libstdcxx-ng-7.2.0-hdf63c60_3 ...
installing: libffi-3.2.1-hd88cf55_4 ...
installing: ncurses-6.1-hf484d3e_0 ...
installing: openssl-1.0.2o-h20670df_0 ...
installing: tk-8.6.7-hc745277_3 ...
installing: xz-5.2.4-h14c3975_4 ...
installing: yaml-0.1.7-had09818_2 ...
installing: zlib-1.2.11-ha838bed_2 ...
installing: libedit-3.1.20170329-h6b74fdf_2 ...
installing: readline-7.0-ha6073c6_4 ...
installing: sqlite-3.23.1-he433501_0 ...
installing: asn1crypto-0.24.0-py36_0 ...
installing: certifi-2018.4.16-py36_0 ...
installing: chardet-3.0.4-py36h0f667ec_1 ...
installing: idna-2.6-py36h82fb2a8_1 ...
installing: pycosat-0.6.3-py36h0a5515d_0 ...
installing: pycparser-2.18-py36hf9f622e_1 ...
installing: pysocks-1.6.8-py36_0 ...
installing: ruamel_yaml-0.15.37-py36h14c3975_2 ...
installing: six-1.11

--2021-11-29 02:10:20--  https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.18.200.79, 104.18.201.79, 2606:4700::6812:c94f, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.18.200.79|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh [following]
--2021-11-29 02:10:20--  https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.130.3, 104.16.131.3, 2606:4700::6810:8303, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.130.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 58468498 (56M) [application/x-sh]
Saving to: ‘Miniconda3-4.5.4-Linux-x86_64.sh’

     0K .......... .......... .......... .......... ..........  0% 79.3M 1s
    50K .......... .......... .......... .......... ..........  0%

In [ ]:
import sys
_ = (sys.path.append("/usr/local/lib/python3.6/site-packages"))

In [ ]:
!python -V

Python 3.6.5 :: Anaconda, Inc.


In [9]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0


In [11]:
!nvidia-smi

Wed Dec  1 18:15:20 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   33C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
%cd /content/drive/MyDrive/autodo

/content/drive/MyDrive/autodo


In [ ]:
!pip install -U -r requirements.txt

Requirement already up-to-date: numpy in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (1.19.5)
Requirement already up-to-date: scipy in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 3)) (1.5.4)
Requirement already up-to-date: scikit-learn in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 4)) (0.24.2)
    100% |████████████████████████████████| 11.5MB 4.5MB/s 
    100% |████████████████████████████████| 5.8MB 9.3MB/s 
Requirement already up-to-date: torch>=1.6.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 7)) (1.10.0)
    100% |████████████████████████████████| 23.3MB 2.3MB/s 
  Using cached https://files.pythonhosted.org/packages/6d/ea/fcc3e64977446c9e27a8e2aca1070c495a0f660a57644ce680b95dd72ddc/kornia-0.6.1-py2.py3-none-any.whl
Requirement not upgraded as not directly required: joblib>=0.11 in /usr/local/lib/python3.6/site-packages (from scikit-learn->-r requirements.txt (line 

In [ ]:
!pip install ipykernel

    100% |████████████████████████████████| 122kB 8.3MB/s 
    100% |████████████████████████████████| 133kB 37.4MB/s 
    100% |████████████████████████████████| 788kB 27.8MB/s 
    100% |████████████████████████████████| 430kB 33.2MB/s 
    100% |████████████████████████████████| 81kB 34.5MB/s 
    100% |████████████████████████████████| 1.1MB 26.4MB/s 
    100% |████████████████████████████████| 92kB 40.0MB/s 
    100% |████████████████████████████████| 61kB 31.6MB/s 
    100% |████████████████████████████████| 1.0MB 25.8MB/s 
    100% |████████████████████████████████| 378kB 36.5MB/s 
    100% |████████████████████████████████| 1.4MB 21.5MB/s 
    100% |████████████████████████████████| 112kB 41.7MB/s 


In [ ]:
!python3 implicit-augment.py -r run0 --gpu 0 -nr 0.1 -ir 100 --dataset SVHN --aug-model SEP --los-model BOTH --hyper-opt HES

In [ ]:
from sklearn.model_selection import StratifiedShuffleSplit
import numpy as np
import random
total_images = 10
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4],[1, 2],
              [3, 4], [1, 2], [3, 4],[4,5],[4,5]])#训练数据集10*2
y = np.array([0, 0, 1, 1, 0, 0, 1, 1, 2, 2])#类别数据集10*1

sss = StratifiedShuffleSplit(n_splits=3, test_size=4, random_state=42)
sss = sss.split(list(range(total_images)), y)
for _ in range(random.randint(1,3)):
  train_index, valid_index = next(sss)
  print("TRAIN_INDEX:", train_index, "TEST_INDEX:", test_index)
  X_train, X_test = X[train_index], X[test_index]#训练集对应的值
  y_train, y_test = y[train_index], y[test_index]
#ss=StratifiedShuffleSplit(n_splits=3,test_size=0.25,random_state=42)#分成2组，测试比例为0.25
print('---------------------------------------')
for train_index, test_index in sss:
    print("TRAIN_INDEX:", train_index, "TEST_INDEX:", test_index)#获得索引值
    X_train, X_test = X[train_index], X[test_index]#训练集对应的值
    y_train, y_test = y[train_index], y[test_index]#类别集对应的值
    


TRAIN_INDEX: [9 1 7 2 3 4] TEST_INDEX: [0 9 6 5]
TRAIN_INDEX: [6 4 0 7 1 8] TEST_INDEX: [0 9 6 5]
TRAIN_INDEX: [1 4 3 7 8 2] TEST_INDEX: [0 9 6 5]
---------------------------------------


In [ ]:
print(list())

[]


In [ ]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
import shutil
shutil.move('/content/drive/MyDrive/PyTorch-VAE/models/vanilla_vae.py','/content/drive/MyDrive/autodo/VAE')

'/content/drive/MyDrive/autodo/VAE/vanilla_vae.py'

In [ ]:
import torch
c=torch.Tensor([[1,2,3],[2,3,4]])
a=torch.ones([2,3,2,2])*2
print(a.shape)

b=a*(c[:,:,None,None])
print(b)

torch.Size([2, 3, 2, 2])
tensor([[[[2., 2.],
          [2., 2.]],

         [[4., 4.],
          [4., 4.]],

         [[6., 6.],
          [6., 6.]]],


        [[[4., 4.],
          [4., 4.]],

         [[6., 6.],
          [6., 6.]],

         [[8., 8.],
          [8., 8.]]]])


In [ ]:
import torch.nn.functional as F
import torch.nn as nn

s = torch.Tensor([[1],[2]])

weights = torch.tensor([[0.5, 0.5, 0.5],
                        [0.5, 0.5, 0.5],
                        [0.5, 0.5, 0.5]])
nb_channels = 3

x = torch.ones(2, nb_channels, 7, 7)
a, b, c=x.shape
print(b)

weights_list = []
for _ in range(2):
  weight = nn.Parameter(s[_]*weights.unsqueeze(0).unsqueeze(0).repeat(3,1,1,1))
  weights_list.append(weight)

outputs=[]
for idx in range(2):
  input = x[idx:idx+1]
  filt = weights_list[idx]
  output = F.conv2d(input, filt, groups=3, padding='same')
  outputs.append(output)

outputs = torch.stack(outputs)
outputs = outputs.squeeze(1)
print(outputs)



ValueError: ignored

In [ ]:
from scipy.ndimage import gaussian_filter
import numpy as np
a=gaussian_filter(np.zeros([5,5]),1)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np
import scipy.stats as st
import torch

def gkern(kernlen=21, nsig=3):
    """Returns a 2D Gaussian kernel."""

    x = np.linspace(-nsig, nsig, kernlen+1)
    kern1d = np.diff(st.norm.cdf(x))
    kern2d = np.outer(kern1d, kern1d)
    return torch.Tensor(kern2d/kern2d.sum())

print(gkern(5,1))

tensor([[0.0287, 0.0363, 0.0393, 0.0363, 0.0287],
        [0.0363, 0.0460, 0.0498, 0.0460, 0.0363],
        [0.0393, 0.0498, 0.0539, 0.0498, 0.0393],
        [0.0363, 0.0460, 0.0498, 0.0460, 0.0363],
        [0.0287, 0.0363, 0.0393, 0.0363, 0.0287]])


In [ ]:
def ikern(kernlen=5):
  x = torch.zeros([kernlen, kernlen])
  x[int((kernlen - 1)/2), int((kernlen - 1)/2)] = 1
  return x

print(ikern(7))

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])


In [ ]:
a = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a=a.view([-1,2,2])
print(a)

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])


In [ ]:
!git clone https://github.com/AntixK/PyTorch-VAE.git

Cloning into 'PyTorch-VAE'...
remote: Enumerating objects: 809, done.
remote: Total 809 (delta 0), reused 0 (delta 0), pack-reused 809
Receiving objects: 100% (809/809), 46.45 MiB | 30.61 MiB/s, done.
Resolving deltas: 100% (582/582), done.


In [ ]:
import torch
print(torch.ones(1))

tensor([1.])


In [1]:
%cd /content/sample_data

/content/sample_data


In [19]:
from PIL import Image

im = Image.open("9.PNG")
ig=im.transform(im.size, Image.AFFINE, (1,0))
print(im.format, im.size, im.mode)
display(im)
display(ig)



ValueError: ignored

In [26]:
import torch.nn.functional as F
import torch
print(F.one_hot(torch.arange(0, 5),5))

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])


In [29]:
import torch.nn as nn
a=nn.LogSoftmax(dim=1)
b=torch.rand([4,5])
print(b)
c=a(b)
print(c)

tensor([[6.5961e-02, 9.4980e-01, 7.3098e-01, 4.8326e-01, 1.3088e-01],
        [5.2415e-01, 5.6082e-01, 8.4412e-01, 5.4754e-01, 9.1428e-01],
        [1.7800e-01, 1.4982e-01, 9.8748e-01, 6.5288e-01, 1.0079e-04],
        [1.6967e-01, 3.9362e-01, 8.3778e-01, 9.0468e-01, 9.4187e-01]])
tensor([[-2.0731, -1.1893, -1.4081, -1.6558, -2.0082],
        [-1.7775, -1.7409, -1.4576, -1.7542, -1.3874],
        [-1.8967, -1.9249, -1.0872, -1.4218, -2.0746],
        [-2.1344, -1.9104, -1.4662, -1.3993, -1.3622]])


In [37]:
a=torch.Tensor([[1,2,3],[4,5,6]])
b=a.repeat([2,2,2])
print(b.shape)
print(b)

torch.Size([2, 4, 6])
tensor([[[1., 2., 3., 1., 2., 3.],
         [4., 5., 6., 4., 5., 6.],
         [1., 2., 3., 1., 2., 3.],
         [4., 5., 6., 4., 5., 6.]],

        [[1., 2., 3., 1., 2., 3.],
         [4., 5., 6., 4., 5., 6.],
         [1., 2., 3., 1., 2., 3.],
         [4., 5., 6., 4., 5., 6.]]])


In [8]:
import torch
n=[1,2,3,1]
m=[1,2,3]
a=[e+1 for e in m]
print(a)

[2, 3, 4]
